{% set version = '0.6.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xlsxjars
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xlsxjars_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xlsxjars/xlsxjars_{{ version }}.tar.gz
  sha256: 37c1517f95f8bca6e3514429394d2457b9e62383305eba288416fb53ab2e6ae6

build:
  merge_build_host: True  # [win]
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rjava
  run:
    - r-base
    - r-rjava

test:
  commands:
    - $R -e "library('xlsxjars')"           # [not win]
    - "\"%R%\" -e \"library('xlsxjars')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=xlsxjars
  license: GPL-3.0-only
  summary: The xlsxjars package collects all the external jars required for the xlxs package.
    This release corresponds to POI 3.10.1.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: xlsxjars
# Type: Package
# Title: Package required POI jars for the xlsx package
# Version: 0.6.1
# Date: 2014-08-21
# Depends: rJava
# LazyLoad: yes
# Authors@R: c(person(c("Adrian", "A."), "Dragulescu",  role = c("aut", "cre"), email = "adrian.dragulescu@gmail.com"),  person("The Apache Software Foundation",  role = c("ctb", "cph"),  comment = "Apache POI, Apache XMLBeans", "Apache Commons Codec"),  person("MetaStuff, Ltd.",  role = c("ctb", "cph"), comment = "Dom4j"))
# Description: The xlsxjars package collects all the external jars required for the xlxs package. This release corresponds to POI 3.10.1.
# License: GPL-3
# Copyright: See file COPYRIGHTS
# NeedsCompilation: no
# Repository: CRAN
# Packaged: 2014-08-21 21:18:37 UTC; adrian
# Author: Adrian A. Dragulescu [aut, cre], The Apache Software Foundation Apache Commons Codec [ctb, cph] (Apache POI, Apache XMLBeans), MetaStuff, Ltd. [ctb, cph] (Dom4j)
# Maintainer: Adrian A. Dragulescu <adrian.dragulescu@gmail.com>
# Date/Publication: 2014-08-22 07:19:16
