appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PqaeeNg2ny+jP21L4nsNtUDQUKuq8jpL1eUU+N1FFMINIaRZ/F4WfLQfcY4PAhrh8DUpwD0Y/sDRvURR/Tw4ZpTInYFChwf3N5HFPks4ubSqgxj0lqYF5C6velm0FvDF6nj86LY0FTjNgWKKYTDq6qJpSh9yHnntYz39lVsMHto6ktroWhAoBiRaSDr+f7XZirYzFioxmq5qnGeBSeEOkw96sFwqiirS4f6104sXAff8b+q2TAo1XVFiGdHSnmiXKCyTpjmbZ34E2TDOZQze7O550wtlCDtGBHV/geTUF/kpG2XIQfa4n2euTDewlyjue9aPZ4dULLKe+BQa6gGenvohykOu3iJAeY/OOD4Fnmbn4pZiXAGpXWi1Ee0OJ8TD6fVlGsldo3+wb2rREjuE8/Y2pXLVfjCAjUPlBlGulgNXHeyo5WwsUbS2m8ZwZ+kVmxtebQ7uthmgyeErQlOBqcSD9ZRBePEb6Erz2hz/GnzFw5O2CC21sxrjCdVxE/EATjR49PJSRNJ7O+ywCEroiriVV7/52oCOFCsTvNg2PfEfRqiKYIUVE6NzWcp4dgEvIFJlDXiZTOrvWZ5gBk9dbV6zSrdurdusUdEdIlgB6c7nCox7TTu4Wo00jUEeFzllHYSc7O+YEEKacDbzI+OhMV/E6wbUSJrjfjn/P0n7LmA=
